## PCLP3  Laboratorul 3 : NumPy


- Andrei-Daniel Voicu: <andrei.voicu133@gmail.com>
- Mihai Nan: <mihai.nan@upb.ro>

## Ce este NumPy?

**NumPy** este un pachet Python folosit în principal pentru calcul științific și numeric. Este foarte popular în rândul oamenilor de știință din domeniul datelor și al analiștilor pentru eficiența sa și gama largă de operații pe array-uri pe care le oferă.

In [2]:
import numpy as np

# Definirea unui tablou unidimensional
a = np.array([1,2,3])
print(type(a))
print(a)

# Definirea unui tablou bidimensional, cu elemente de tip float
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print(b)

<class 'numpy.ndarray'>
[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


## De ce utilizam NumPy?

| Avantaje | Dezavantaje |
| --- | --- |
| Operații vectorizate eficient | Necesită timp pentru a-l învăța |
| Simplificarea lucrului cu tablouri multi-dimensionale | Listele NumPy sunt omogene |
| Gamă largă de funcții matematice | Suport restrâns pentru alte tipuri decât cele numerice |
| Performanțe uluitoare | Nu este adecvat pentru colectii de date tabelare (unde pot lipsi valori) |

Mai întâi, să luăm în considerare modul în care listele Python și vectorii Numpy stochează datele. O listă Python stochează elemente ca obiecte separate, fiecare poate fi de orice tip. Cu toate acestea, un vector NumPy este un vector de tip omogen, ceea ce înseamnă că toate elementele din vector sunt de același tip, reducând semnificativ utilizarea memoriei.

De exemplu, să presupunem că dorim să stocăm un interval de 1000 de numere întregi. Să comparăm utilizarea memoriei unei liste Python și a unui vector Numpy:

In [ ]:
import sys
import numpy as np

list_of_numbers = []
for i in range(1000000):
    list_of_numbers.append(i)
sys.getsizeof(list_of_numbers)

arr = np.zeros((1000000,))
for i in range(1000000):
    arr[i] = i

print(sys.getsizeof(list_of_numbers))
print(sys.getsizeof(arr))

8448728
8000104


Acum să trecem la viteza de calcul. Deoarece Numpy utilizează blocuri continue de memorie, acesta poate profita de operațiunile vectorizate, care sunt procesate utilizând instrucțiuni SIMD (Single Instruction, Multiple Data). Acest lucru duce la calcule mai rapide. Listele Python, pe de altă parte, nu beneficiază de acest lucru din cauza stocării lor împrăștiată în memorie .

In [3]:
import numpy as np
import time

# Define two Python lists
py_list1 = list(range(1000000))
py_list2 = list(range(1000000, 2000000))

# Define two Numpy arrays
np_array1 = np.arange(1000000)
np_array2 = np.arange(1000000, 2000000)

# Adding Python lists
start_time = time.time()
result_list = [a + b for a, b in zip(py_list1, py_list2)]
print("Time taken to add Python lists: ", time.time() - start_time)

# Adding Numpy arrays
start_time = time.time()
result_array = np_array1 + np_array2
print("Time taken to add Numpy arrays: ", time.time() - start_time)

Time taken to add Python lists:  0.0630643367767334
Time taken to add Numpy arrays:  0.007475614547729492


## Operatii NumPy

### Operații matematice

In [ ]:
arr1 = np.array([7, 3, 2, 6, 5])
arr2 = np.array([2, 5, 1, 4, 10])

# Operații matematice
arr_add = arr1 + arr2
arr_sub = arr1 - arr2
arr_mul = arr1 * arr2
arr_div = arr1 / arr2

print(f"Adunare: {arr_add}")
print(f"Scadere: {arr_sub}")
print(f"Inmultire: {arr_mul}")
print(f"Impartire: {arr_div}")

# Funcții statistice
mean = np.mean(arr1)
sum = np.sum(arr1)
max = np.max(arr1)
min = np.min(arr1)

print(f"Medie: {mean}")
print(f"Suma: {sum}")
print(f"Max: {max}")
print(f"Min: {min}")

Adunare: [ 9  8  3 10 15]
Scadere: [ 5 -2  1  2 -5]
Inmultire: [14 15  2 24 50]
Impartire: [3.5 0.6 2.  1.5 0.5]
Medie: 4.6
Suma: 23
Max: 7
Min: 2


### Transformări

Extragerea elementelor este identică cu extragerea elementelor din listele Python clasice:

In [ ]:
# Extragerea unui element din vector.
a = np.array([4,6,9])
print(a[0])

# Extragerea unui element in cazul unui tablou multi-dimensional.
a = np.array([(1,2,3), (4,5,6)], dtype = int)
print(a[0][1])

4
2


Putem sa utilizăm "slicing" tot în același mod cum utilizăm pe listele Python.

In [ ]:
a = np.array( [4,6,9] )
print(a[0:2])

O funcționalitate foarte puternică o reprezintă posibilitatea filtrării datelor printr-o expresie logică (formă și mai compactă asemănătoare cu list comprehensions).

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Crearea unei copii.
numbers_copy = numbers.copy()

# Modificarea valorilor pare la 0.
numbers_copy[numbers % 2 == 0] = 0

print(numbers_copy)

Există și câteva funcții des utilizate pentru a modifica forma tablourilor.

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transformă array-ul 2D într-unul 1D
flattened = arr.flatten()

# Transpune array-ul 2D
transposed = arr.T

# Transformă array-ul 2D într-unul 1D
reshaped = arr.reshape(1, 9)

print(f"Flatten: {flattened}")
print(f"Transpose:\n {transposed}")
print(f"Reshape: {reshaped}")

Flatten: [1 2 3 4 5 6 7 8 9]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Reshape: [[1 2 3 4 5 6 7 8 9]]


## Exerciții propuse

1. Construiți un vector cu primele 16 numere naturale nenule. Pentru acest vector aplicați o operație care să-l transforme într-o matrice cu 4 linii și 4 coloane.

In [31]:
arr = np.array(range(1,17))
print(arr)
reshape = arr.reshape((4, 4))
print(reshape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


2. Pornind de la matricea definită la exercițiul anterior, scrieți instrucțiuni pentru afișarea elementelor colorate în următoarea imagine.

<a href="https://ibb.co/mNtNfh5"><img src="https://i.ibb.co/qJ9JTmY/Screenshot-from-2024-04-22-01-19-12.png" alt="Screenshot-from-2024-04-22-01-19-12" border="0"></a>

In [45]:
print(reshape[1][2:4])
print(reshape[0:4, 1])
print(reshape[2:4, 2:4])
print(reshape[1][0], end =' ')
print(reshape[1][2], end =' ')
print(reshape[3][0], end =' ')
print(reshape[3][2], end =' ')

[7 8]
[ 2  6 10 14]
[[11 12]
 [15 16]]
5 7 13 15 

3. Implementați funcția care calculează descompunerea $L \cdot U$ pentru o matrice $A$. Pentru acest lucru, urmăriți pașii:

1. Inițializăm matricea $L$ cu matricea identitate $I$.
2. Inițializăm $U$ cu $A$
3. Pentru $i = 1, \dots, n$
	4. Pentru $j = i+1, \dots, n$
		5. $L_{ji} = \frac{U_{ji}}{U_{ii}}$
		6. $U_j = (U_j - L_{ji}U_{i})$, unde $U_{i}$ reprezintă linia $i$ din $U$   
7. Returnăm tuplul cu $L$ și $U$

In [61]:
def lu(A):
    n = np.size(A, 1)
    L = np.eye(n)
    U = A
    for i in range(n):
      for j in range(i + 1, n):
        L[j][i] = U[j][i]/U[i][i]
        U[j] = U[j] - L[j][i] * U[i]
    return [L, U]
A = np.array([[1,2,3],[2, 3, 4],[3, 4, 5]])
[L,U] = lu(A)
print(L)
print(U)


[[1. 0. 0.]
 [2. 1. 0.]
 [3. 2. 1.]]
[[ 1  2  3]
 [ 0 -1 -2]
 [ 0  0  0]]


4. Implementați o funcție care preia ca input un array unidimensional și returnează o matrice bidimensională. Transformarea din array unidimensional în matrice bidimensională se va face folosind conceptul de "strides" sau pași.
Pentru context, fiecare "pas" reprezintă o deplasare în array-ul unidimensional, iar "lungimea ferestrei" indică numărul de elemente din array care vor fi incluse în fiecare sub-array al matricei bidimensionale.

**Hint:**
  *numpy.lib.stride_tricks*

In [79]:
def gen_strides(a, stride_len, window_len):
  n = np.size(A)
  rows = (n - window_len)//stride_len + 1
  a_s = np.zeros((rows, window_len))
  idx = 0
  for i in range(rows):
    for j in range(window_len):
      a_s[i][j] = a[idx + j]
    idx = idx + stride_len
  return a_s
A = np.array([1,2,3,4,5,6,7], dtype=np.int32)
print(gen_strides(A, 2, 3))

[[1. 2. 3.]
 [3. 4. 5.]
 [5. 6. 7.]]


5. Citiți de la intrare două matrici de dimensiuni diferite, prima de dimensiune (n, m) și a doua de dimensiune (p, q). Implementați o funcție care să calculeze și să returneze produsul Kronecker între cele două matrici introduse.

**Intrare:**
- Prima linie conține două numere întregi, n și m, reprezentând dimensiunile primei matrici.
- Următoarele n linii conțin câte m numere fiecare, reprezentând elementele primei matrici.
- Linia următoare conține două numere întregi, p și q, reprezentând dimensiunile celei de-a doua matrici.
- Următoarele p linii conțin câte q numere fiecare, reprezentând elementele celei de-a doua matrici.

**Ieșire:**
- Matricea rezultată din calcularea produsului Kronecker între cele două matrici introduse.


**Hint:**
- Produsul Kronecker între două matrici este o operație care combină două matrici pentru a produce o nouă matrice. Mai multe detalii despre cum se calculează produsul Kronecker între două matrici puteți găsi [aici](https://en.wikipedia.org/wiki/Kronecker_product).
- În Python, produsul Kronecker între două matrici se poate calcula cu ajutorul funcției numpy.kron.

In [88]:
def p_kron(a,b):
  m, n = a.shape
  p, q = b.shape
  rez = np.zeros((m*p, n*q))
  for i in range(m*p):
    for j in range(n*q):
      rez[i][j] = a[i//p][j//q]*b[i%p][j%q]
  return rez
A = np.array([[1,2],[2, 3],[3, 4]])
B = np.array([[1,2,3],[2, 3, 4]])
print(p_kron(A,B))
print(np.kron(A,B))

[[ 1.  2.  3.  2.  4.  6.]
 [ 2.  3.  4.  4.  6.  8.]
 [ 2.  4.  6.  3.  6.  9.]
 [ 4.  6.  8.  6.  9. 12.]
 [ 3.  6.  9.  4.  8. 12.]
 [ 6.  9. 12.  8. 12. 16.]]
[[ 1  2  3  2  4  6]
 [ 2  3  4  4  6  8]
 [ 2  4  6  3  6  9]
 [ 4  6  8  6  9 12]
 [ 3  6  9  4  8 12]
 [ 6  9 12  8 12 16]]


6. Implementați un algoritm de detecție a contururilor dintr-o imagine folosind operatorul Sobel. Programul ar trebui să încarce o imagine de la intrare, să aplice filtrul Sobel pentru a detecta marginile și apoi să salveze imaginea rezultată.

**Hint:**
- Operatorul Sobel: https://homepages.inf.ed.ac.uk/rbf/HIPR2/sobel.htm
  

In [89]:
import numpy as np
from PIL import Image
import cv2

def sobel_edge_detection(img):
    # TODO 6
    sobel_x = np.array([[-1, 0, 1],
                        [-2, 0, 2],
                        [-1, 0, 1]])

    sobel_y = np.array([[-1, -2, -1],
                        [ 0,  0,  0],
                        [ 1,  2,  1]])
    grad_x = cv2.filter2D(img, -1, sobel_x)
    grad_y = cv2.filter2D(img, -1, sobel_y)
    gradient_magnitude = np.sqrt(np.square(grad_x) + np.square(grad_y))
    gradient_magnitude = gradient_magnitude / gradient_magnitude.max() * 255
    gradient_magnitude = gradient_magnitude.astype(np.uint8)

def main():
    # Load the image
    img = Image.open("test.png").convert('L')
    img = np.array(img)

    # Apply Sobel edge detection
    sobel_img = sobel_edge_detection(img)

    # Convert the result to an image and save it
    sobel_img = Image.fromarray(sobel_img)
    sobel_img.convert('RGB').save("output.jpg")

if __name__ == "__main__":
    main()

FileNotFoundError: [Errno 2] No such file or directory: 'test.png'